#!/bin/bash

mkdir -p www
rm -rf www/*
for page in web/*.html; do
  if [ "$page" != "web/base.html" ]; then
    source $page
    export TITLE CONTENT
    envsubst < web/base.html > www/$(basename $page)
  fi
done
